### ISSUE TITLE
Doesn't work on Linux based systems because of the of process filters

### ISSUE THREAD

**Issue by Thulium-Drake** [jcleveland/clevels-valheim-mods#2]
When starting my Linux based server, I receive the following message in the log:

```
Apr 06 22:18:42 steam start_server_bepinex.sh[15602]: [Warning:   BepInEx] Skipping [BeastsOfBurden 1.0.3] because of process filters (valheim.exe)
```

Is this mod Windows-only?

**Comment by jcleveland** [comment]
Hi thanks for reaching out. For the current version of the mod only the clients should need to have it installed. If you only have it installed on the clients and you're still having issues please let me know.

**Comment by Thulium-Drake** [comment]
In that case, yes, as I also play the game on Linux :-) and I was unable to hook up the cart to a boar I tamed ^^

**Comment by jcleveland** [comment]
I'm assuming you see a similar message when starting the client in Linux? 

I'll do some digging today. I believe if I just remove this line https://github.com/jcleveland/clevels-valheim-mods/blob/master/BeastsOfBurden/BeastsOfBurden.cs#L11 it will remove the process filter and everything should work for you (assuming other mods work okay for you). I can try to put up a test version of the dll without that line on my lunch break today. 

I'm new to using BepinEx and want to make sure that filter doesn't have some deeper more important role that is alluding me at the moment before making a general release. I'm not doing anything that should be any more windows dependent than any other mod so based on my very limited knowledge of mono this should just work.

**Comment by jcleveland** [comment]
@Thulium-Drake I just uploaded a new DLL here: https://github.com/jcleveland/clevels-valheim-mods/releases/tag/BoBv1.0.4rc1 I think it will correct your issue but I don't have Valheim configured on Linux to test it myself.

**Comment by Thulium-Drake** [comment]
Hi @jcleveland ,

Thanks for the quick fix! I have been playing with it for a couple of hours now, works exactly as planned. Even in Multiplayer :-)
